import type { Metadata } from 'next';

import { headers } from 'next/headers';
import { redirect } from 'next/navigation';

import Provider from '@/src/app/Provider';
import { authOptions } from '@/src/app/api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const proxyHeaders = await headers();
  const url = proxyHeaders.get('x-url');
  const currentPathname = new URL(url || '').pathname;

  const session = await getServerSession(authOptions);

  // 리다이렉트 제외할 경로
  const publicPaths = ['/login'];

  if (!publicPaths.includes(currentPathname) && !session?.user.id) {
    redirect('/login');
  }

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
